trainer_type: XLALmTrainer

collator_type: packed
dataset: fineweb-2024-packed
stream_dataset: true

sequence_length: 512

bs: 1024
mini_bs: 64

checkpoint_interval: 5000
save_optimizer: false

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 500
    num_training_steps: 20000

    lr: 0.0006
    final_lr: 0.00006

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.1
